### ISSUE TITLE
Ensure that sand is supported by sandstone

### ISSUE THREAD

**Issue by tacotexmex** [Treer/cloudlands#1]
Desert cloudlands renders with no stone support underneath sand nodes. Hence massive chunks of sand starts falling when interacted with:

![screenshot_20180612_145730](https://user-images.githubusercontent.com/25328789/41291841-0b92f202-6e51-11e8-863f-b672729a0be7.png)
![screenshot_20180612_145738](https://user-images.githubusercontent.com/25328789/41291842-0bafa938-6e51-11e8-8f4c-b52fa8f1866f.png)

**Comment by Treer** [comment]
The fix doesn't affect the layer on the very surface, so it's still possible to have some crumbly edges, but they will be small.

**Comment by tacotexmex** [comment]
Excellent, thanks.
