### ISSUE TITLE
Enormous tree sometimes cut

### ISSUE THREAD

**Issue by tacotexmex** [Treer/cloudlands#2]
![screenshot_20190224_140540](https://user-images.githubusercontent.com/25328789/53299697-ddfcbf00-383d-11e9-9395-d38c8c9af3a7.png)
🤔

**Comment by Treer** [comment]
This is that place_schematic() bug, I think schemlib avoids it by avoiding place_schematic() and placing every block with lua. I may have a go at adding schemlib support after I quickly fix the issue with place_schematic() failing to invalidate the replacement table cache (needed for proper tree varieties).

Approaching slowly from a distance seems to often avoid the place_schematic() bug - I guess it startles easily.

**Comment by Treer** [comment]
v1.42 practically fixes this, and schemlib support is also provided now if it's still a problem.
